bigquery:
  project_id: "ecomagent-opsfleet"
  dataset_id: "bigquery-public-data.thelook_ecommerce"
agent:
  llm_model: "gemini-2.5-flash"
  fallback_llm_model: "gemini-2.0-flash"
  temperature: 0.3
  max_iterations: 5
logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(name)s  - %(message)s"